name: Build and publish to GitHub Pages

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_run:
    workflows: ["Docker build"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: false

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: 
      image: ${{ github.env.REGISTRY }}/${{ github.env.IMAGE_NAME }}:${{ github.ref_name }}
      options: --user root
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Build website
        run: myst build --html
        env:
          BASE_URL: ${{ steps.deployment.outputs.page_url }}

      # Deploy the book's HTML to gh-pages branch
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: _build/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
